*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -308,7 +308,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE PKG_CONFIG GTK_CFLAGS GTK_LIBS GTK_CONFIG SDL_CONFIG SDL_CFLAGS SDL_LIBS CPP EGREP LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE PKG_CONFIG GTK_CFLAGS GTK_LIBS GTK_CONFIG SDL_CONFIG SDL_CFLAGS SDL_LIBS GNOME_CFLAGS GNOME_LIBS WITH_GNOME_TRUE WITH_GNOME_FALSE CPP EGREP LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -855,6 +855,7 @@ Optional Features:
   --disable-gtktest       Do not try to compile and run a test GTK program
   --disable-sdl      Don't look for the SDL library
   --disable-sdltest       Do not try to compile and run a test SDL program
+  --enable-gnome    Turn on gnome
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -1623,7 +1624,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=gtkboard
- VERSION=0.10.9
+ VERSION=0.11
 
 
 cat >>confdefs.h <<_ACEOF
@@ -3488,6 +3489,161 @@ echo "$as_me: WARNING: *** SDL version $SDL_VERSION not found. Sound will be dis
 	LIBS="$LIBS $SDL_LIBS -lSDL_mixer"
 fi
 
+gnome=false
+
+GNOME_CFLAGS=""
+GNOME_LIBS=""
+
+# Check whether --enable-gnome or --disable-gnome was given.
+if test "${enable_gnome+set}" = set; then
+  enableval="$enable_gnome"
+
+	if test "x$enableval" = "xyes"; then
+		gnome=true
+	fi
+
+fi;
+
+if test "$gnome" = true ; then
+
+  succeeded=no
+
+  if test -z "$PKG_CONFIG"; then
+    # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_PKG_CONFIG" && ac_cv_path_PKG_CONFIG="no"
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+
+if test -n "$PKG_CONFIG"; then
+  echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
+echo "${ECHO_T}$PKG_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  fi
+
+  if test "$PKG_CONFIG" = "no" ; then
+     echo "*** The pkg-config script could not be found. Make sure it is"
+     echo "*** in your path, or set the PKG_CONFIG environment variable"
+     echo "*** to the full path to pkg-config."
+     echo "*** Or see http://www.freedesktop.org/software/pkgconfig to get pkg-config."
+  else
+     PKG_CONFIG_MIN_VERSION=0.9.0
+     if $PKG_CONFIG --atleast-pkgconfig-version $PKG_CONFIG_MIN_VERSION; then
+        echo "$as_me:$LINENO: checking for
+			libgnome-2.0 >= 2.0.0
+			libgnomeui-2.0 >= 2.0.0
+	" >&5
+echo $ECHO_N "checking for
+			libgnome-2.0 >= 2.0.0
+			libgnomeui-2.0 >= 2.0.0
+	... $ECHO_C" >&6
+
+        if $PKG_CONFIG --exists "
+			libgnome-2.0 >= 2.0.0
+			libgnomeui-2.0 >= 2.0.0
+	" ; then
+            echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+            succeeded=yes
+
+            echo "$as_me:$LINENO: checking GNOME_CFLAGS" >&5
+echo $ECHO_N "checking GNOME_CFLAGS... $ECHO_C" >&6
+            GNOME_CFLAGS=`$PKG_CONFIG --cflags "
+			libgnome-2.0 >= 2.0.0
+			libgnomeui-2.0 >= 2.0.0
+	"`
+            echo "$as_me:$LINENO: result: $GNOME_CFLAGS" >&5
+echo "${ECHO_T}$GNOME_CFLAGS" >&6
+
+            echo "$as_me:$LINENO: checking GNOME_LIBS" >&5
+echo $ECHO_N "checking GNOME_LIBS... $ECHO_C" >&6
+            GNOME_LIBS=`$PKG_CONFIG --libs "
+			libgnome-2.0 >= 2.0.0
+			libgnomeui-2.0 >= 2.0.0
+	"`
+            echo "$as_me:$LINENO: result: $GNOME_LIBS" >&5
+echo "${ECHO_T}$GNOME_LIBS" >&6
+        else
+            GNOME_CFLAGS=""
+            GNOME_LIBS=""
+            ## If we have a custom action on failure, don't print errors, but
+            ## do set a variable so people can do so.
+            GNOME_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "
+			libgnome-2.0 >= 2.0.0
+			libgnomeui-2.0 >= 2.0.0
+	"`
+            echo $GNOME_PKG_ERRORS
+        fi
+
+
+
+     else
+        echo "*** Your version of pkg-config is too old. You need version $PKG_CONFIG_MIN_VERSION or newer."
+        echo "*** See http://www.freedesktop.org/software/pkgconfig"
+     fi
+  fi
+
+  if test $succeeded = yes; then
+     :
+  else
+     { { echo "$as_me:$LINENO: error: Library requirements (
+			libgnome-2.0 >= 2.0.0
+			libgnomeui-2.0 >= 2.0.0
+	) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&5
+echo "$as_me: error: Library requirements (
+			libgnome-2.0 >= 2.0.0
+			libgnomeui-2.0 >= 2.0.0
+	) not met; consider adjusting the PKG_CONFIG_PATH environment variable if your libraries are in a nonstandard prefix so pkg-config can find them." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+	GNOME_CFLAGS="$GNOME_CFLAGS -DHAVE_GNOME=1"
+fi
+
+
+
+
+
+
+if test "x$gnome" = "xtrue"; then
+  WITH_GNOME_TRUE=
+  WITH_GNOME_FALSE='#'
+else
+  WITH_GNOME_TRUE='#'
+  WITH_GNOME_FALSE=
+fi
+
+
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -4448,6 +4604,13 @@ echo "$as_me: error: conditional \"AMDEP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${WITH_GNOME_TRUE}" && test -z "${WITH_GNOME_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"WITH_GNOME\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"WITH_GNOME\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
@@ -5032,6 +5195,10 @@ s,@GTK_CONFIG@,$GTK_CONFIG,;t t
 s,@SDL_CONFIG@,$SDL_CONFIG,;t t
 s,@SDL_CFLAGS@,$SDL_CFLAGS,;t t
 s,@SDL_LIBS@,$SDL_LIBS,;t t
+s,@GNOME_CFLAGS@,$GNOME_CFLAGS,;t t
+s,@GNOME_LIBS@,$GNOME_LIBS,;t t
+s,@WITH_GNOME_TRUE@,$WITH_GNOME_TRUE,;t t
+s,@WITH_GNOME_FALSE@,$WITH_GNOME_FALSE,;t t
 s,@CPP@,$CPP,;t t
 s,@EGREP@,$EGREP,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
@@ -5647,5 +5814,31 @@ if test "$no_create" != yes; then
   # Use ||, not &&, to avoid exiting from the if with $? = 1, which
   # would make configure fail if this is the last instruction.
   $ac_cs_success || { (exit 1); exit 1; }
+fi
+
+
+echo " "
+
+if test $enable_gtk2 = "yes" ; then
+	echo "$as_me:$LINENO: result: GTK2 enabled." >&5
+echo "${ECHO_T}GTK2 enabled." >&6
+else
+	echo "$as_me:$LINENO: result: GTK2 disabled." >&5
+echo "${ECHO_T}GTK2 disabled." >&6
+fi
+
+if test $enable_sdl = "yes" ; then
+	echo "$as_me:$LINENO: result: SDL enabled." >&5
+echo "${ECHO_T}SDL enabled." >&6
+else
+	echo "$as_me:$LINENO: result: SDL disabled." >&5
+echo "${ECHO_T}SDL disabled." >&6
+fi
+if test $enable_gnome = "yes" ; then
+	echo "$as_me:$LINENO: result: GNOME enabled." >&5
+echo "${ECHO_T}GNOME enabled." >&6
+else
+	echo "$as_me:$LINENO: result: GNOME disabled." >&5
+echo "${ECHO_T}GNOME disabled." >&6
 fi
 
